$ErrorActionPreference = "Stop"

function Convert-ToCMakePath {
  param([Parameter(Mandatory = $true)][string]$PathValue)
  return $PathValue.Replace("\", "/")
}

function Convert-ToEnvPathLiteral {
  param([Parameter(Mandatory = $true)][string]$PathValue)
  return $PathValue.Replace("\", "\\")
}

function Convert-ToBase64 {
  param([Parameter(Mandatory = $true)][string]$Value)
  return [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($Value))
}

function Write-GeneratedConfig {
  param(
    [Parameter(Mandatory = $true)][string]$RepoRoot,
    [Parameter(Mandatory = $true)][string]$FlutterRoot,
    [Parameter(Mandatory = $true)][string]$GeneratedConfigPath
  )

  $packageConfig = Join-Path $RepoRoot ".dart_tool\package_config.json"
  if (-not (Test-Path $packageConfig)) {
    throw "Missing package config: $packageConfig"
  }

  $pubspecFile = Join-Path $RepoRoot "pubspec.yaml"
  $versionLine = Get-Content $pubspecFile | Where-Object { $_ -match '^version:\s*(.+)$' } | Select-Object -First 1
  if (-not $versionLine) {
    throw "Could not find version in $pubspecFile"
  }

  $appVersion = ($versionLine -replace '^version:\s*', '').Trim()
  $semanticVersion = $appVersion
  $buildNumber = "0"
  if ($appVersion -match '^(?<version>[^+]+)\+(?<build>.+)$') {
    $semanticVersion = $Matches.version
    $buildNumber = $Matches.build
  }

  $versionParts = $semanticVersion.Split(".")
  while ($versionParts.Count -lt 3) {
    $versionParts += "0"
  }

  $flutterTool = Join-Path $FlutterRoot "bin\flutter.bat"
  $flutterVersionInfo = & $flutterTool --version --machine | ConvertFrom-Json
  if ($LASTEXITCODE -ne 0) {
    throw "Failed to query Flutter version."
  }

  $dartDefines = @(
    "FLUTTER_VERSION=$($flutterVersionInfo.frameworkVersion)",
    "FLUTTER_CHANNEL=$($flutterVersionInfo.channel)",
    "FLUTTER_GIT_URL=$($flutterVersionInfo.repositoryUrl)",
    "FLUTTER_FRAMEWORK_REVISION=$($flutterVersionInfo.frameworkRevision)",
    "FLUTTER_ENGINE_REVISION=$($flutterVersionInfo.engineRevision)",
    "FLUTTER_DART_VERSION=$($flutterVersionInfo.dartSdkVersion)"
  ) | ForEach-Object { Convert-ToBase64 $_ }

  $ephemeralDir = Split-Path -Parent $GeneratedConfigPath
  New-Item -ItemType Directory -Force -Path $ephemeralDir | Out-Null

  $flutterRootCmake = Convert-ToCMakePath $FlutterRoot
  $repoRootCmake = Convert-ToCMakePath $RepoRoot

  $flutterRootEnv = Convert-ToEnvPathLiteral $FlutterRoot
  $repoRootEnv = Convert-ToEnvPathLiteral $RepoRoot
  $ephemeralEnv = Convert-ToEnvPathLiteral $ephemeralDir
  $packageConfigEnv = Convert-ToEnvPathLiteral $packageConfig

  $configContent = @"
# Generated by scripts/build_windows.ps1. Do not commit.
file(TO_CMAKE_PATH "$flutterRootCmake" FLUTTER_ROOT)
file(TO_CMAKE_PATH "$repoRootCmake" PROJECT_DIR)

set(FLUTTER_VERSION "$appVersion" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR $($versionParts[0]) PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR $($versionParts[1]) PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH $($versionParts[2]) PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD $buildNumber PARENT_SCOPE)

list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=$flutterRootEnv"
  "PROJECT_DIR=$repoRootEnv"
  "FLUTTER_EPHEMERAL_DIR=$ephemeralEnv"
  "FLUTTER_TARGET=lib\\main.dart"
  "DART_DEFINES=$($dartDefines -join ',')"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=true"
  "PACKAGE_CONFIG=$packageConfigEnv"
)
"@

  Set-Content -Path $GeneratedConfigPath -Value $configContent -Encoding UTF8
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$flutterRoot = if ($env:FLUTTER_ROOT) {
  $env:FLUTTER_ROOT
} else {
  "C:\tools\flutter"
}
$vsDevCmd = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
$pluginRoot = Join-Path $repoRoot "windows\flutter\ephemeral\.plugin_symlinks"
$generatedConfigPath = Join-Path $repoRoot "windows\flutter\ephemeral\generated_config.cmake"
$buildDir = Join-Path $repoRoot "tmp_build\cmake_nmake"
$runnerDir = Join-Path $buildDir "runner"
$distDir = Join-Path $repoRoot "dist\windows"
$stagingDistDir = Join-Path $repoRoot "dist\windows_next"
$windowsDir = Join-Path $repoRoot "windows"
$dependenciesFile = Join-Path $repoRoot ".flutter-plugins-dependencies"
$cacheFile = Join-Path $buildDir "CMakeCache.txt"
$backupDistDir = Join-Path $repoRoot "dist\windows_prev"

if (-not (Test-Path $flutterRoot)) {
  throw "Flutter SDK not found at $flutterRoot. Set FLUTTER_ROOT or install Flutter there."
}

if (-not (Test-Path $vsDevCmd)) {
  throw "VsDevCmd.bat not found at $vsDevCmd."
}

$flutterTool = Join-Path $flutterRoot "bin\flutter.bat"
$packageConfig = Join-Path $repoRoot ".dart_tool\package_config.json"
if (-not (Test-Path $packageConfig) -or -not (Test-Path $dependenciesFile)) {
  & $flutterTool pub get
  if ($LASTEXITCODE -ne 0) {
    throw "flutter pub get failed with exit code $LASTEXITCODE"
  }
}

if (-not (Test-Path $dependenciesFile)) {
  throw "Missing .flutter-plugins-dependencies after pub get."
}

New-Item -ItemType Directory -Force -Path $pluginRoot | Out-Null
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null

if (Test-Path $stagingDistDir) {
  Remove-Item $stagingDistDir -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $stagingDistDir | Out-Null

Get-Process vision_draft,flutter,dart,cmake,nmake,cl,link,rc,mt -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Milliseconds 800

if (Test-Path $cacheFile) {
  Remove-Item $cacheFile -Force
}

Write-GeneratedConfig -RepoRoot $repoRoot -FlutterRoot $flutterRoot -GeneratedConfigPath $generatedConfigPath

$deps = Get-Content $dependenciesFile -Raw | ConvertFrom-Json
$windowsPlugins = @($deps.plugins.windows) + @($deps.plugins.windows_ffi)
$windowsPlugins = $windowsPlugins | Where-Object { $_ -and $_.name -and $_.path } | Sort-Object name -Unique

foreach ($plugin in $windowsPlugins) {
  $name = $plugin.name
  $target = $plugin.path.TrimEnd("\")
  $linkPath = Join-Path $pluginRoot $name

  if (Test-Path $linkPath) {
    $item = Get-Item $linkPath -Force
    if ($item.LinkType -eq "Junction") {
      cmd /c rmdir "$linkPath" | Out-Null
    } elseif ($item.PSIsContainer -or $item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
      Remove-Item $linkPath -Recurse -Force
    } else {
      throw "Existing non-link path blocks plugin junction: $linkPath"
    }
  }

  cmd /c mklink /J "$linkPath" "$target" | Out-Null
}

$configure = @(
  "`"$vsDevCmd`"",
  "-arch=x64",
  "-host_arch=x64",
  ">nul",
  "&&",
  "cmake",
  "-S", "`"$windowsDir`"",
  "-B", "`"$buildDir`"",
  "-G", "`"NMake Makefiles`"",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DFLUTTER_TARGET_PLATFORM=windows-x64",
  "-DFLUTTER_ROOT=`"$flutterRoot`""
) -join " "

$build = @(
  "`"$vsDevCmd`"",
  "-arch=x64",
  "-host_arch=x64",
  ">nul",
  "&&",
  "cmake",
  "--build", "`"$buildDir`"",
  "--config", "Release",
  "&&",
  "cmake",
  "--install", "`"$buildDir`"",
  "--config", "Release"
) -join " "

cmd.exe /d /s /c $configure
if ($LASTEXITCODE -ne 0) {
  throw "CMake configure failed with exit code $LASTEXITCODE"
}

cmd.exe /d /s /c $build
if ($LASTEXITCODE -ne 0) {
  throw "CMake build/install failed with exit code $LASTEXITCODE"
}

$runtimeEntries = @(
  "vision_draft.exe",
  "flutter_windows.dll",
  "pdfium.dll",
  "file_selector_windows_plugin.dll",
  "printing_plugin.dll",
  "sqlite3_flutter_libs_plugin.dll",
  "sqlite3.dll",
  "data"
)

foreach ($entry in $runtimeEntries) {
  $source = Join-Path $runnerDir $entry
  if (-not (Test-Path $source)) {
    throw "Missing runtime artifact: $source"
  }
  Copy-Item -Path $source -Destination $stagingDistDir -Recurse -Force
}

$placeholderAssetsDir = Join-Path $stagingDistDir "data\flutter_assets\assets\placeholders"
if (Test-Path $placeholderAssetsDir) {
  Remove-Item $placeholderAssetsDir -Recurse -Force
}

foreach ($artifact in @("CMakeFiles", "Makefile", "cmake_install.cmake")) {
  $artifactPath = Join-Path $stagingDistDir $artifact
  if (Test-Path $artifactPath) {
    Remove-Item $artifactPath -Recurse -Force
  }
}

if (Test-Path $backupDistDir) {
  Remove-Item $backupDistDir -Recurse -Force
}
if (Test-Path $distDir) {
  Move-Item -Path $distDir -Destination $backupDistDir -Force
}
Move-Item -Path $stagingDistDir -Destination $distDir -Force
if (Test-Path $backupDistDir) {
  Remove-Item $backupDistDir -Recurse -Force
}

Write-Host ""
Write-Host "Done."
Write-Host "EXE: $(Join-Path $runnerDir 'vision_draft.exe')"
Write-Host "DIST: $distDir"
